name: 'Terraform Plan (Dev)'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yml'

# Ensure only one workflow runs at a time to prevent state lock conflicts
concurrency:
  group: terraform-plan-dev-${{ github.ref }}
  cancel-in-progress: false

env:
  TERRAFORM_VERSION: '1.13.4'
  WORKING_DIRECTORY: './terraform'

jobs:
  terraform-plan:
    name: 'Terraform Plan (Dev Environment)'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'Azure Login with OIDC'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: 'Terraform Format Check'
        run: terraform fmt -check -recursive
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: 'Terraform Init'
        run: terraform init -backend-config="key=dev/terraform.tfstate"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: 'Terraform Validate'
        run: terraform validate
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: 'Terraform Plan'
        run: terraform plan -no-color -out=tfplan -var-file="terraform.dev.tfvars"
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          TF_VAR_subscription_id_nautilus: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: 'Generate Plan Text Output'
        run: terraform show -no-color tfplan > tfplan.txt
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: 'Comment PR with Plan Output'
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('${{ env.WORKING_DIRECTORY }}/tfplan.txt', 'utf8');
            
            const output = `#### Terraform Plan (Dev Environment) 📋
            \`\`\`
            ${plan}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
